### ISSUE TITLE
Finish the Buy Now workflow

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#116]
Need to finish up the buy now workflow on the product page so we can begin testing that that works on Google shopping

**Comment by diveddie** [comment]
Necesitamos terminar el flujo de trabajo para la pagina de producto. Aquí esta los diseños, en pagina 7 y 8:

https://xd.adobe.com/view/b13b6bd4-f42e-47db-a8f7-70ef42752e9a-e468/screen/c5a0112a-8904-4f1e-aa65-9b31e679e38c/?x_product=cc-slack%2F1.5.0

**Comment by eduardorr97** [comment]
the buy now workflow on the product is done imo, if there are issues/bugs on this lets handle it in another issue with a bit more context, closing this, ofc feel free to reopen if needed
