### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#122]
We need the current privacy policy for Confirm Biosciences and then we need to create a privacy policy page. Maybe this comes from Sanity so that it's easy to update in the future.

**Comment by devconfirm** [comment]
Yes we'll set this up as a "Simple" page type. I can get that set up.

**Comment by eduardorr97** [comment]
Added in #165
At the moment the sanity Simple Page only contains some `lorem ipsum` text, the gatsby app has the logic to render said content in the `/privacy-policy` route, this issue can be closed, feel free to reopen if needed
