### ISSUE TITLE
Review how to add PDFs to sanity so they are easily linkable

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#154]
PDFs need to live in Sanity and have a URL that they want to be able to share.

**Comment by eduardorr97** [comment]
Created a PDFs hub in sanity with the ability to copy downloadable/shareable link to clipboard, can be found under Global Assets > Files Hub

Closing this, feel free to comment or reopen this issue

cc: @devconfirm
