### ISSUE TITLE
Product Page Buy Now / Bulk Form Accordion

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#156]
The Buy Now / Bulk Order form should be an accordion, and is on the same page.

**Comment by jorgearellano19** [comment]
![Captura de Pantalla 2020-09-18 a la(s) 15 31 26](https://user-images.githubusercontent.com/22033154/93646727-0752e200-f9c4-11ea-8c3c-621f0deb7f08.png)

You mean this cards?

**Comment by eduardorr97** [comment]
@diveddie can we get a little bit more context on this please?

**Comment by diveddie** [comment]
https://react-bootstrap.github.io/components/accordion/

Just spoke with Moises about this as well in Slack.

**Comment by eduardorr97** [comment]
As of this date, the buy now components are an accordion, closing this, feel free to reopen, if there are issues regarding Product Buy flow, lets handle it in another issue with more context
