### ISSUE TITLE
Hitting Product Page Does Not Show Proper Styles

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#157]
If you go directly to the product page from a link, the styles are not properly loaded. For example:

https://confirm-biosciences-production.netlify.app/product/10-panel-t-cup-clia-waived-urine-drug-test-cup/

We should review that all pages are properly loading all global styles.

**Comment by eduardorr97** [comment]
Fixed in #161, can be closed, feel free to reopen if needed
