### ISSUE TITLE
Service Image / Text should be link / NEED URL

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#172]
I think the images and the text for the services should be linkable.

Can we get the link inserted to test functionality?

I also think these need to open in new tabs since they will link externally (@devconfirm please confirm)

**Comment by eduardorr97** [comment]
Just added a link pointing to google.com to the `Certified Studies` and can confirm that it opens in a new tab and the image is also clickable, should that be enough to close this?
