### ISSUE TITLE
Product.tsx isMobile event listener

### ISSUE THREAD

**Issue by diveddie** [confirmbiosciences/confirm-biosciences#22]
In the Product.tsx file, you need to make sure you set up an event listener so that the proper component is displayed if the window is resized. It won't work well if we only render it once. The event listener will be setup in a useEffect hook, and you can also clean up the event listener. We can review this on Monday if you have any questions.

**Comment by eduardorr97** [comment]
Please check #23

**Comment by eduardorr97** [comment]
Closing since #23 was merged
