### ISSUE TITLE
Work on the Pages responsiveness

### ISSUE THREAD

**Issue by eduardorr97** [confirmbiosciences/confirm-biosciences#5]
Check the Collection and Product pages and look for responsiveness issues, I noticed there's a white thin line showing on mobile at the edge of the screen on the right, usually this is caused by an element (or group of elements) with a `width` set bigger than the screen.

Find those elements and fix them so the white thin line doesn't show anymore

Also make sure every element is aligned at `20px` from both left and right, headings font-sizes are responsive using `rem` as unit.

**Comment by eduardorr97** [comment]
Lets check on some visuals in mobile version:
- In `CollectionDescription` component the image should expand across the screen, `collection title` should have a font-size responsive
- The `ProductCardsContainer` has a `padding-top` of `80px`, in mobile should be `40px`, same for the `margin-bottom`
- The `LearnMore` component should have in `padding: 40px` in all directions
- The `FAQ` title has a fixed `margin-bottom: 80px`, should be responsive to `40px` in mobile

**Comment by jorgearellano19** [comment]
#15
